baseurl: https://suppe-og-analyse.netlify.app/
title: Suppe og analyse
author: Eivind Hageberg
canonifyurls: yes
languagecode: no
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Suppe og analyse - test
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Hjem
      url: /
      weight: 1
    - name: Om meg
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/gardenberg
      weight: 3
    - name: RSS
      url: /index.xml
      weight: 4
