---
title: Veit du hva banken din gjør?
author: Eivind
date: '2013-02-27'
slug: veit-du-hva-banken-din-gjør
categories:
  - finans
tags:
  - attac
---

Attac har i lengre tid arbeidet med bankenes rolle i finanskrisa, og blant annet fått utredet en rapport om bankenes tilknytning til skatteparadis og uetiske investeringer (se Attac.no-oppslaget her). Jeg skrev utkast til en uttalelse som, med noen endringer, ble vedtatt på Attac Norges landsmøte 27. februar, og som senere har blitt sent ut som leserbrev.

Europa er rammet av en gjeldskrise med massearbeidsledighet, kutt i offentlig velferd og angrep på sosiale rettigheter som resultat. Gjeldskrisa ble utløst da de europeiske bankenes skadelige spekulasjon og tvilsomme utlånspraksis slo tilbake på bankene. De kom da løpende til staten for å bli reddet fra de frie markedskreftene og konkurs.

Attac Norge mener at bankene har et ansvar overfor samfunnet som helhet til å fordele ressursene slik at de på best mulig måte støtter opp under hensyn til sosiale rettigheter, miljø og menneskerettigheter. Vi har dokumentert at de største norske bankene ikke tar sitt samfunnsansvar på alvor. I en gjennomgang av utlån og investeringer fra DNB, Nordea, Danske Bank og Handelsbanken fant vi at alle bankene har tilknytning til flere skatteparadis, finansierer våpenproduksjon og miljøverstinger. Noen hadde også tilknytning til matvarespekulasjon og selskaper involvert i korrupsjon.

Med kontorer og filialer i skatteparadiser som Luxembourg, Sveits, Cayman Islands og City of London mener vi at det ikke er tvil om at norske banker støtter et system som bidrar til hemmelighold, tilrettelegger for skatteunndragelser, og hemmer utvikling i Sør. Ti ganger verdien av verdens bistandsmidler forsvinner fra fattige land på grunn av dette systemet. Verdier tilsvarende 35 oljefond er gjemt bort i slike jurisdiksjoner, midler som trengs sårt i disse vanskelige økonomiske tider. Dette systemet kan ikke norske banker være med på å opprettholde.

Vi er imidlertid ikke maktesløse, og Attac Norge vil derfor oppfordre:

- Deg til å spørre banken din om hva den gjør med pengene dine, hvorfor den er aktiv i skatteparadis, og hvem den låner ut penger til. Er du ikke fornøyd med svarene, bytt bank.
- Banker og finansforetak til å støtte opp under sosiale rettigheter, miljø og menneskerettigheter, gå ut av skatteparadis, og følge samme regler for samfunnsansvar for utlån som for investeringer.
- Norske myndigheter til å kreve at bankene offentliggjør mottakerne av større utlån, og kreve land-for-land-rapportering av norsk finansnæring.
