---
title: Om en mulig handelsavtale mellom EU og USA
author: Eivind
date: '2013-08-07'
slug: om-en-mulig-handelsavtale-mellom-eu-og-usa
categories:
  - landbruk
tags:
  - handelspolitikk
---

erdens største handelspartnere, EU og USA, begynte mandag 8. juli formelt første runde i forhandlingene om en frihandelsavtale, Transatlantic Trade and Investment Partnership (TTIP). Runden fant sted i Washington DC, og skulle gå igjennom alle områder som kan komme til å bli omfattet av avtalen.

Her følger litt info om forhandlingene, og noen kjappe betraktninger rundt mulige konsekvenser. Dette bygger på et orienteringsnotat jeg skrev for noen uker siden, så det er ganske faktatungt.

Dette er avtale som har vært snakket om en stund, i følge EU-observerer har handelsbyråkrater i EU ønsket seg dette de siste 20 årene. Den kommer etter at en High-Level Working Group (HLWG) fra Transatlantic Economic Council anbefalte en slik avtale, etter å ha sett på muligheten for å øke handel og investeringer fra 2011 til 2013. Grunndokumentet fra denne gruppa ligger til grunn for forhandlingene. Neste runde finner sted 7. oktober i Brüssel.

EUObserverer sier at begge sider ønsker en avtale før slutten av 2014 (datoer å holde øye med er nyvalget av president for kommisjonen september 2014 og midterm-valg av kongress november 2014). Dette omtales av observatører, ministre og forhandlingsledere som å være veldig ambisiøst. Til sammenligning har forhandlinger om en frihandelsavtale mellom Canada og EU foregått siden 2010.

NUPI-direktør Sverdrup går i Dagens Næringsliv 24. juni hardt ut og kaller avtalen «et transatlantisk EØS», og referer også til betegnelser som «et økonomisk NATO» og «mother of all FTAs». Forventningene til omfanget er altså store. Det kan være verdt å merke seg at TTIP kommer samtidig med at USA forhandler om en Trans-Pacific Partnership in Asia med bl.a. Japan, (ikke Kina). Obama må være ute etter å skrive seg inn i historiebøkene før 2016.

Mandat og omfang
Handelsministrene i EU godkjente forhandlingsmandatet 14. juni. En lekket versjon av mandatet fastslår at målet med avtalen er å oppnå «gjensidig liberalisering av handel med varer og tjenester, så vel som handelsrelaterte regler, med et høyt ambisjonsnivå over eksisterende forpliktelser i WTO». Offentlig tilgjengelig info bekrefter dette, EU har mandat til å framforhandle en avtale som omhandler 1) markedsadgang, 2) konvergens av regler og 3) handelsregler for «delte globale utfordringer». Mandatet inkluderer dermed toll, opphavsregler, tjenester, investeringer, offentlige innkjøp, tekniske handelshindringer, sanitære forhold, IP, og geografisk opphavsbetegnelser på alle områder. (For ytterligere info har Kommisjonen publisert en rekke posisjonsdokumenter med tekniske posisjoner).

På den amerikanske sida melder EUObserver at en avtale til nå har støtte i Kongressen. Til nå er det lite tilgjengelig informasjon om mandatet, informasjonen som ligger ute framhever overfladisk studert det samme som infoen fra EU og HLWG.

De involverte partene og analytikere sier gjerne at det generelle tollnivået mellom EU og USA allerede er svært lavt (i følge Kommisjonen/WTO i snitt ca. 5,2 % i EU og 3.5 % i USA). De største gevinstene antas derfor å måtte innebære en konvergens i reguleringer. Dette kan innebære harmonisering av regler, eller gjensidig godkjennelse av regler.

EUObserver forventer at finanstjenester, mat og landbruk kan bli blant de vanskeligste områdene. I tillegg forventer de mer overordna at konvergens av reguleringer vil bli et vanskelig tema. Transporttjenester, offentlig innkjøp og standarder i farmasiindustiren har også vært kontroversielle i forhandlinger mellom EU og USA tidligere.

Godkjenning av en endelig avtale
En avtale må godkjennes av Kongressen før den kan ratifiseres – og Kongressen har også rett til å vedta endringer, noe som gjør handelsavtaler vanskelig. Obama kan få tillatelse til å «Fast track»/»trade promotion authority», som innebærer at Kongressen kun kan si ja eller nei, og har ytret håp om å få til dette. Verdt å merke at representantenes hus og 1/3 av Senatet skal på valg november 2014.

Mandatet er tildelt Kommisjonen (DG Trade, DGT) fra Rådet. Et forhandlingsresultat må godkjennes av Rådet og Parlamentet, før det blir bindende. Kommunikasjon mellom DGT, EC og EP under forhandlingene blir dermed sentralt. En skal ikke undervurdere skillelinjer mellom de 28 EU-landene. Før det første forhandlingsmandatet ble godkjent, var Frankrike ute og krevde at audiovisuelle tjenester skal være utenfor forhandlingsmandatet, «l’exeption culturelle». EUObserverer mener dette kan være symbolsk motstand, basert på en dypere skepsis mot frihandelsavtaler.

Landbruk en del av avtalen?
EU og USA er verdens største importører og eksportører av landbruksvarer. Handel med jordbruksprodukter forventes å bli et at de vanskeligste forhandlingsområdene i TTIP, men lite er kjent om konkrete posisjoner enda. Diskusjonene om ikke-tollbaserte handelshindre forventes å bli problematiske (kapittelet om Sanitære og phytosanitære spørsmål, SPS, ser ut til å være sentralt). Disse omfatter bl. a. nasjonale lover og regler, krav til dokumentasjon og bruk av standarder. Eksempler på forskjeller som kan være krevende er:

    Genetisk modifiserte organismer (GMO)
    Bruk og anerkjennelse av merkeordningen «beskyttede betegnelser», lovbeskytte IP/produktbetegnelser på næringsmidler
    Regelverk knyttet til bruk av veksthormoner i produksjon (Disputt i WTOs tvisteløsningssystem)
    Vasking av kylling med klor.
    I tillegg har vi spørsmål som dyrevelferd, eksportsubsidier.

Konsekvenser av avtalen for omverdenen – økonomi
Håp om økonomisk vekst som konsekvens kan være en viktig drivmotor for disse forhandlingene,. særlig for veksthungrige EU-politikere. Det er flere estimater på hva en slik avtale kan gi av gevinster. Euobserver siterer en utredning fra Kommisjonen, som slår fast at en avtale kan øke Eus eksport til USA med 28 %, og være verdt 119 milliarder euro per år for EU totalt (0.5%-0.4% høyere BNP). USA kan få 80 milliarder euro per år og 2 millioner nye jobber. Hvis avtalen ikke omfatter annet enn toll, anslås det at fordelene vil være betraktelig lavere (tollnivået mellom de to landene er allerede svært lave på en rekke varer).

Det finnes flere økonomiske analyser av konsekvensene av en slik avtale. En studie som har fått spalteplass i Aftenposten og DN via NUPI ble utført av Ifo, og publisert av Bertelsmann-stiftung. Studien gjør estimater (computational general equilibrium) av effekter av fjerning av all toll, og fjerning av ikke-tollbaserte handelshindringer på EU, USA og tredjeland. Konklusjonen her er USA og EU-land vil kunne tjene på avtalen (særlig en dyptgripende avtale), mens land som står utenfor (som Norge), vil kunne tape. Norge vil på lengre sikt kunne miste 11 500 arbeidsplasser hvis liberaliseringen går langt (gitt en rekke forutsetninger, og usikkerhetsmomentene tatt i betraktning er det lite vits å henge seg opp i tallet, og heller fokusere på retningen). Dette er gitt en rekke forutsetninger, blant annet «alt annet likt». En større standardisering mellom EU og USA vil sannsynligvis kunne påvirke Norge gjennom EØS-avtalen.

Denne typen beregninger er også blitt kritisert for å gjøre urealistiske antakelser om dynamiske effekter av handel, og det er gjort få studier tidligere av reduksjoner av ikke-tollbaserte handelshindringer – studien ser ut til å anta at disse blir store, basert på andre avtaler.

Et minst like interessant spørsmål enn hvem som vil tjene på den og hvem som vil tape på den. I en artikkel på Euobserverer kommenterer Ferdi de Ville at Sør-Europa etter innførselen av Euroen har sett økende handelsunderskudd og forholdsvis lav eksportandel av BNP, mens Nord-Europa (og særlig Tyskland) har hatt overskudd på handelsbalansen. Hun kommenterer at det er lite trolig at dette vil endres, selv med økt markedsadgang til USA (i motsetning til Ifo, som finner store fordeler særlig for Sør-Europa).

Keynesiansk sett bygger de positive anslagene på at økt eksport skal gjøre opp for fallet i etterspørsel drevet av kuttpolitikk. Kan både EU og USA frihandle seg til økonomisk vekst gjennom positiv handelsbalanse samtidig? Har intern devaluering i Sør-Europa gått så langt at de er konkurransedyktige på internasjonale (og nasjonale) markeder?

Andre konsekvenser
Nasjonale myndigheters suverenitet vil også bli påvirket. Hvor mye avhenger av omfanget i endringer, tilpasninger eller godkjenninger av ulike reguleringer. EU-Mandatet legger opp til en dynamisk avtale, hvor målet er å utvikle øke harmoniseringen av regler gradvis over tid – altså bygge inn en gjensidig forpliktelse til regel-konvergens. Her er det også verdt å se etter hvorvidt en ISDS-mekanisme inkluderes i avtalen (ISDS: Investor-state dispute settlement – private firmaer gis mulighet til å gå til sak mot visse typer inngripen fra nasjonale myndigheter).

Omfattende forhandlinger kan også åpne opp rom for forsøk på endringer av regler i EU, slik f.eks. forventninger om sluttføring av Doha-runden har bidratt til endringer i CAP.

Mer geopolitisk/strategisk kan TTIP sees som et forsøk på å demme opp for Kina og Indias innflytelse, sette en ny standard for hva som omfattes i handelsavtaler, samt etablere felles europeiske og amerikanske standarder som gjeldende i internasjonal handel. Hvis da EU og USA forhandler seg sammen om posisjoner, hvor de tidligere hadde ulike syn, kan dette også påvirke forhandlinger i WTO – eller sette nye standarder for internasjonal handel.

Konsekvenser for sosiale standarder? Forskjeller i f.eks. ratifiserte ILO-konvensjoner? EU-dokumentene slår fast at de ikke ønsker å fire på standardene, men hvis forskjeller godkjenner, betyr det at dårligere praksis på f.eks. arbeidsrettigheter godkjennes. I hvilken grad kan slikt gi konkurransefordeler innenfor et åpent marked?