---
title: Kritisk journalistikk og den femte statsmakt (kritisk borgerjournalistikk)
author: Eivind
date: '2011-09-16'
slug: kritisk-journalistikk-og-den-femte-statsmakt-kritisk-borgerjournalistikk
categories:
  - journalisme
tags: []
---

Internettet er stort, svært, gigantisk. Noen bør sortere ut et par ting som kan være verdt å lese. Denne uken har jeg valgt ut noen kilder om journalisme.

I et demokrati har Journalisten den svært viktige oppgaven det er å holde oversikt med hvem som får hvilke ressurser, når og hvordan, samt hvorfor dette skjer – for så å informere et størst mulig publikum om det etterpå. Etter å ha jobbet med PR for studentfestivalen ISFiT – verdensstørstestudentfestivalmedtematiskfokus, værsågod – og blant annet fått pressemeldinger direkte skrevet av på dagbladet.no og lest opp på NRK Midt-Norges nyhetssending, så ville jeg vært litt treig hvis jeg ikke ble litt skeptisk til hvordan mediene arbeider. Som Niels Christian Geelmuyden liker å si: ««VIL DERE VITE hva en nyhet er for noe», spurte en kjent amerikansk journalist en gang i tiden. «En nyhet er noe som et eller flere mennesker svært nødig vil at andre skal få kjennskap til.» «Vil dere vite hva resten er», spurte han og viftet med en avis. «Resten er reklame.» (I Aftenposten 2011, om WikiLeaks).

Dette har også Ignacio Ramonet tematisert i uttrykket «den femte statsmakt», som kanskje ble brukt for første gang i et tysk foredrag mai 2005: Den fjerde statsmakt, mediene, har mislykkes i sin rolle som maktkritikere, gravere og sannhetsvoktere, og har blitt sammenblandet med mektige politiske og økonomiske aktører – staten og kapitalen og mediene sitter i samme båt, om du vil.

En svært dyktig journalist som har brukt å si høylydt hva han mener om dette er Robert Fisk (av Vice Magazine betegnet som «A Journalistic God«. Fylt med rettferdig vrede har han langet ut fra Beirut, blant annet mot hvordan utenriksdekning i vestlige (i hovedsak engelske og amerikanske) medier overtar statlige synspunkt og statlig språk, og blir dermed et verktøy for reprodusering av England og USAs propanganda rundt Afghanistan, Irak, Palestina, Israle – eller for Tyrkias fornektelse av folkemordet på armenerne. The New York Times kunne vært omdøpt til «Official say» uttalte han under et foredrag en gang.

Herman og Chomskys «Manufacturing Consent» fra 1988 tar for seg hvordan profittorientering, maktkonsentrering, annonsørenes makt, store aktørers informasjonsmakt, protester, interesseorganisasjoner og antikommunisme eller krigen mot terror hindrer mediene i å oppfylle sitt egentlige oppdrag. Joakim Møllersen, styremedlem i Radikalt Økonominettverk, hadde i mars i år en god artikkel om problemstillingen på Dagsavisens «Nye Meninger»-side.

Ramonets forslag til en løsning på problemene som han, Herman og Chomsky skisserer er kritisk borgerjournalisme, muliggjort blant annet gjennom informasjonsrevolusjonen og bloggen. Dette ble også plukket opp av Civitas daværende nestleder Finn Bergersen, som riktignok mente uttrykket kom fra CNN (og ikke radikaleren Ramonet): Bergersen snakker blandt annet om hvordan bloggen er iferd med å innta rampelyset som viktig journalistisk verktøy, og anbefaler nordmenn å ta en titt på dette nye fenomenet. Seks år er tydeligvis mange år på internett – men ikke for mange, Bergersens tips om å kikke på Global Voices (en blogg med bloggere som rapporterer om innholdet i blogger i hele verden) er fortsatt et godt tips.