---
title: Innføringsartikkel om WTO
author: Eivind
date: '2011-10-03'
slug: innføringsartikkel-om-wto
categories:
  - handelspolitikk
tags:
  - attac
---

Av en eller annen grunn ender jeg ofte opp med å skrive innføringsartikler. Coca Cola-saken, WTO, finansmarkeder og Attac er noe av det jeg har forsøkt å forklare på trykk tidligere. Her kommer en artikkel om WTO, publisert i Taklinger nr. 7 i 2007. Artikkelen kunne absolutt trenge en oppdatering og kildeangivelser, selv om dette neppe er noe jeg kommer til å prioritere.

Det er interessant å se at Pascal Lamy 19. september var ute og erklærte at det igjen var full stopp i den nå ti år gamle Doha-runden (Kilde: Abc-nyheter). At journalisten (Lamy var det ikke) benytter anledningen til å erklære WTO-rundens død  tror jeg er forhastet, siden Lamy tydeligvis arbeider med andre måter å bevege forhandlingene framover på (noe bl.a. den indiske delegasjonen kommenterer her) – men forskjellene er store, og maktbalansen mellom utviklede land, BRICS og utviklingsland er nok grundig forandret siden 1999.

WTO – Hva nytt kan man si?

30. november 1999. Regnet høljer ned i Seattle. I gatene utenfor noen møtelokaler er 100 000 demonstranter samlet for å protestere mot urettferdighet. Kamprop, faner og protestmarsj. Til tross for tåregass, gummikuler og politivold er protestene så høylydte at ministerkonferansen i Verdens Handelsorganisasjon bryter sammen, ute av stand til å sette i gang en ny forhandlingsrunde.

Attac og WTO er begge barn av den økonomiske globaliseringen, men er langtifra glade i hverandre. Setter en seg ned og leser en artikkel om WTO med Attac-vinkling kan en fort få inntrykk av at det er djevelen som blir omtalt i særdeles lite smigrende ordlag. Det kan derfor være på tide å ta et skritt tilbake, og se på hva Verdens Handelsorganisasjon egentlig er.

WTO fra A til Å
WTO (uttales dåbbeltveteo), Verdens Handelsorganisasjon, ble oppretta i januar 1995 som en avløsning av GATT. GATT var den internasjonal hovedavtalen om handel og toll som ble innført i 1948. Sammen med en rekke andre tiltak skulle GATT sørge for at de internasjonale økonomiske kreftene skapte vekst, enighet og fred, ikke kollaps, uenighet, og krig.

Hvorvidt perioden fra 1940 til 1990 var preget av enighet og fred kan selvsagt diskuteres, men vekst og endring var så absolutt tilstede. Teknologiske framskritt gjorde verden mindre, handelen økte, og ønsket om økt handel økte enda mer. Med økt handel ble land mer gjensidige avhengig av hverandre. Denne prosessen er den økonomisk globaliseringa.

I forsøket på å håndtere den økonomiske globaliseringa utviklet GATT, opprinnelig kun et avtaleverk, seg etterhvert til en semi-institusjon. Denne semi-institusjonen var imidlertid hverken sterk eller omfattende nok til å håndtere det stadig økende ønsket om internasjonal handel. Et vilkår for at internasjonal handel skal fungere, er nemlig trygghet og stabilitet i det internasjonale markedet. Internasjonal handel vil dermed være tjent med internasjonale institusjoner, som kan forhandle fram avtaler, håndheve regler og fungere som legitime møteplasser. Både stater, transnasjonale selskap og økonomer innså dermed at det trengtes et nytt mutilateralt avtaleverk for frihandel som var bedre tilpasset den økte økonomiske globaliseringa. Dermed ble WTO opprettet.

I dag er så godt som alle verdens handlende land medlem av WTO. Organisasjonen har hovedkvarter og sekretariat i Geneve, med rundt 500 ansatte. Det viktigste organet er ministermøtet som blir avholdt annethvert år. WTOs arbeidsoppgaver er å forvalte og overvåke handelsreglene, løse handelskonflikter og være et forum for videre forhandlinger av handelsregler.

WTOs formål
WTOs mål er ifølge vedtektene deres å øke den økonomiske veksten i alle medlemsland gjennom å redusere toll og andre handelshindringer, liberalisere verdenshandelen og skape et forutsigbart, regelbasert handelssystem basert på ikke-diskriminering. Ikke-diskriminering vil på norsk si likebehandling av nasjonale og utenlandske bedrifter, og at alle land skal ha like vilkår.

Det internasjonale handelsregelverket WTO regulerer er utviklet gjennom åtte forhandlingsrunder. Dette regelverket innbefatter GATT, handel med varer, GATS, handel med tjenester, og TRIPS, intellektuell eiendomsrett, også kjent som patenter. Det er mange som mener at WTO ved sin rolle i det internasjonale økonomiske systemet er en av de absolutt mektigste internasjonale organisasjonene.

WTOs rolle er dermed å sørge for at alle følger, og bli behandlet likt av, reglene i det internasjonale markedet. Uten en slik garantist vil det være svært fristende for ett land å sette i gang proteksjonistiske tiltak, og dermed tjene penger på handel uten å måtte gi fra seg markedsandeler til andre land. I det flere land tyr til en slik proteksjonistisk strategi, vil det internasjonale økonomiske systemet kunne kollapse.

Interesser
Et av det viktigste poengene ved WTO er at det er en plattform hvor medlemslandene kan forhandle fram handelsavtaler. Disse medlemslandene har selvsagt svært sprikende interesser, og vil gjerne eksportere mer av det de kan konkurrere med, men nødig importere mer på de områdene der konkurranseevnen mangler. Et av de virkelige store problemene med WTO er mangelen på sammenfallende interesser.

En type interesser som kan antas å ha relativt stor gjennomslagskraft er de internasjonale storkonsernene. Store selskaper som Coca Cola, Kraft, og General Motors som har større sluttsummer i regnskapene sine enn flere land. Et eksempel på storselskapenes betydning ser en i TRIPS-reguleringene. TRIPS, eller Handelsrelaterte Aspekter ved Intellektuell Eiendomsrett, er patentlovgivning som er ment å sikre insentiver til utvikling av ny teknologi. Gjennom disse avtalene stiller statene som godkjenner avtalen seg bak kravet fra selskapene om at den som gjør en oppdagelse/oppfinnelse, skal kunne patentere denne, få monopol på ideen og dermed kunne tjene inn igjen det det har kostet å oppdage/oppfinne ideen.

Kritikere hevder imidlertid at dette kan sees som monopolisering av kunnskap. Denne monopoliseringen kan imidlertid være skadelig for U-land, siden den minsker muligheten de har til å tilegne seg teknologi. Det at disse rettighetene er så sterke som de faktisk er, kan tyde på at transnasjonale selskaper og storkonsern har en betydelig innflytelse.

Global rettferd
80% av verdens befolkning må dele 20% av verdens kake. 20% av verdens befolkning har kontroll over 80% av verdens verdier. Rundt en milliard mennesker lever på under én dollar dagen, gudene vet hvor mange som lever på under to, eller tre. Afrika sør for Sahara opplever fortsatt økonomisk stillstand eller tilbakegang. Halvparten av verdens befolkning har aldri holdt en telefon.

Handel blir av mange sett på som et godt verktøy for å rette på situasjonen. WTO har jo da også som mål å skape økt økonomisk vekst i alle sine medlemsland gjennom å liberalisere verdenshandelen. Som en nøkkelinstitusjon og plattform når det kommer til internasjonal handel, burde dermed WTO i teorien kunne bidra til positiv utvikling for de fattigste landene.

I 2001 ble det i Doha, hovedstaden i Quatar, vedtatt en niende forhandlingsrunde, den såkalte utviklingsrunden. En rapport utgitt av SEATINI, Sør og Østafrikansk Handelsinstitutt, som analyserer hvorvidt Doha-runden er en reell utviklingsrunde konkluderer med et rungende «Nei!» De hevder at siden WTO er bygd på prinsippet om likebehandling og gjensidige ytelser mellom medlemslandene, så kan ikke urettferdigheten rettes opp. Skal u-landenes interesser ivaretas, må disse landene særbehandles. Dette har til nå ikke skjedd.

Spørsmålet blir dermed, slik WTO fungerer i dag, hvilke interesser som får gjennomslag og om disse interessene har interesse av at fattige land skal tjene på frihandelsregimet.